/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.apache.flink:flink-java:1.20.0")  // Use the same version as your Flink Docker image
    implementation("org.apache.flink:flink-streaming-java:1.20.0")
    implementation("org.apache.flink:flink-clients:1.20.0")
    implementation("org.apache.flink:flink-connector-base:1.20.0")
    implementation("org.apache.flink:flink-connector-jdbc:3.2.0-1.19")

    implementation("org.postgresql:postgresql:42.7.4")

//    implementation("org.apache.flink:flink-scala_2.12:1.20.0")  // Use the same version as your Flink Docker image
//    implementation("org.apache.flink:flink-streaming-scala_2.12:1.20.0")
//    implementation("org.scala-lang:scala-library:2.12.8")       // Scala version compatible with Flink
}


tasks.withType<JavaCompile> {
    sourceCompatibility = "11"
    targetCompatibility = "11"
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}
